name: usta_bor_android
description: A new Flutter project.

version: 1.0.1+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  css_colors: ^1.1.1
  cupertino_icons: ^1.0.4
  get: ^4.6.5
  flutter_svg: ^1.0.3
  dotted_border: ^2.0.0+2
  flutter_exif_rotation: ^0.5.0
  exif: ^3.1.1
  webview_flutter: ^3.0.1
  image_picker: ^0.8.4+10
  http: ^0.13.4
  cached_network_image: ^3.2.0
  flutter_rating_bar: ^4.0.0
  url_launcher: ^6.0.20
  pin_code_fields: ^7.3.0
  flutter_spinkit: ^5.1.0
  internet_connection_checker: ^0.0.1+3
  flutter_countdown_timer: ^4.1.0
  intl: ^0.17.0
#  alice: ^0.2.1
  retrofit: ^3.0.1+1
  logger: any
  dio: ^4.0.4
  expandable: ^5.0.1
  flutter_local_notifications: ^9.4.0
  keyboard_dismisser: ^3.0.0
  keyboard_actions: ^4.0.0
  flutter_html: ^3.0.0-alpha.2
  badges: ^2.0.2
  get_storage: ^2.0.3
  flutter_typeahead: ^4.0.0
  draggable_home: ^1.0.2
  equatable: ^2.0.3
  flutter_facebook_auth: ^4.3.3
  sign_in_with_apple: ^4.0.0
  crypto: ^3.0.1
  firebase_core: ^1.13.1
  share_plus: ^4.0.4
  fk_user_agent: ^2.1.0
  package_info_plus: ^1.4.2

  #app update
  in_app_update: ^3.0.0
  new_version: ^0.3.0




  #Firebase cloud messaging
  firebase_messaging: ^11.2.11



  #From Mustafo

  #Google Sign In
  firebase_auth: ^3.3.9
  google_sign_in: ^5.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.0.5
  retrofit_generator: ^4.0.1
#    git:
#      url: https://github.com/Chimerapps/retrofit.dart.git
#      ref: 9f90296751984b359937c38563da5b19db5550f5
#      path: generator
#
  build_runner: ^2.1.7

flutter_native_splash:
  color: "#ffffff"
  image: assets/png/logo.png
  android: true

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/png/
    - assets/svg/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300

